# Generated by Django 5.0 on 2024-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDeskription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание города')),
                ('image_city', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
