# Generated by Django 5.0 on 2025-01-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_maindeskription_options_catalogekskursii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogekskursii',
            name='image_excursion',
            field=models.ImageField(upload_to='image_excursion/', verbose_name='Картинка экскурсии'),
        ),
        migrations.AlterField(
            model_name='catalogekskursii',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='mainapp.maindeskription', verbose_name='К какому городу относится'),
        ),
        migrations.AlterField(
            model_name='catalogekskursii',
            name='price_excursion',
            field=models.IntegerField(verbose_name='Цена экскурсии'),
        ),
        migrations.CreateModel(
            name='ModalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_long', models.IntegerField(verbose_name='Сколько длится поездка')),
                ('name_place', models.TextField(max_length=1500, verbose_name='Название локаций и места на выбор с указанием времени')),
                ('time_to_departure', models.IntegerField(verbose_name='Во сколько выезд')),
                ('take_with_you', models.TextField(max_length=500, verbose_name='Что взять с собой')),
                ('how_many_day_and_night', models.CharField(max_length=100, verbose_name='За сколько дней и ночей')),
                ('how_many_people', models.IntegerField(verbose_name='Стоимость за сколько человек')),
                ('price_russian', models.IntegerField(verbose_name='Цена за русскую поездку')),
                ('price_english', models.IntegerField(verbose_name='Цена за английскую поездку')),
                ('what_is_not_included_in_price', models.CharField(max_length=200, verbose_name='Что не входит в стоимость')),
                ('modal_ekskurs_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modal_ekskurs_name', to='mainapp.catalogekskursii')),
            ],
            options={
                'verbose_name': 'Модальные окна',
                'verbose_name_plural': 'Модальное окно',
            },
        ),
    ]
