# Generated by Django 5.0 on 2025-01-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_catalogekskursii_image_excursion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaltext',
            name='how_long',
            field=models.CharField(max_length=100, verbose_name='Сколько длится поездка'),
        ),
        migrations.AlterField(
            model_name='modaltext',
            name='modal_ekskurs_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modal_ekskurs_name', to='mainapp.catalogekskursii', verbose_name='К какой экскурсии отосится'),
        ),
    ]
