# Generated by Django 5.0 on 2025-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_modaltext_how_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaltext',
            name='time_to_departure',
            field=models.CharField(max_length=100, verbose_name='Во сколько выезд'),
        ),
    ]
