# Generated by Django 5.0 on 2025-01-13 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_modaltext_time_to_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaltext',
            name='modal_ekskurs_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modal_texts', to='mainapp.catalogekskursii', verbose_name='К какой экскурсии отосится'),
        ),
    ]
