# Generated by Django 5.0 on 2025-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_modaltext_modal_ekskurs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaltext',
            name='name_place',
            field=models.TextField(max_length=5500, verbose_name='Название локаций и места на выбор с указанием времени'),
        ),
        migrations.AlterField(
            model_name='modaltext',
            name='take_with_you',
            field=models.TextField(max_length=1500, verbose_name='Что взять с собой'),
        ),
    ]
