# Generated by Django 5.0 on 2024-12-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindeskription',
            name='image_city',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка города'),
        ),
    ]
