# Generated by Django 5.0 on 2024-12-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_maindeskription_image_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindeskription',
            options={'verbose_name': 'Главная карточка города', 'verbose_name_plural': 'Главные карточки городов'},
        ),
        migrations.CreateModel(
            name='CatalogEkskursii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_excursion', models.CharField(max_length=100, verbose_name='Название экскурсии')),
                ('price_excursion', models.IntegerField()),
                ('image_excursion', models.ImageField(upload_to='image_excursion/')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='mainapp.maindeskription')),
            ],
            options={
                'verbose_name': 'Экскурсия города',
                'verbose_name_plural': 'Экскурсии городов',
            },
        ),
    ]
